// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using RevelMovies.Infrastructure.Persistence;

#nullable disable

namespace RevelMovies.Infrastructure.Persistence.Migrations;

[DbContext(typeof(RevelMoviesDbContext))]
partial class RevelMoviesDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        modelBuilder.Entity("RevelMovies.Domain.Events.Event", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedNever().HasColumnType("uniqueidentifier").HasColumnName("id");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnType("datetimeoffset").HasColumnName("created_at");
            b.Property<DateTimeOffset?>("EndsAt").HasColumnType("datetimeoffset").HasColumnName("ends_at");
            b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)").HasColumnName("name");
            b.Property<string>("Slug").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)").HasColumnName("slug");
            b.Property<DateTimeOffset?>("StartsAt").HasColumnType("datetimeoffset").HasColumnName("starts_at");
            b.Property<int>("Status").HasColumnType("int").HasColumnName("status");
            b.Property<string>("TimeZone").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)").HasColumnName("time_zone");
            b.Property<DateTimeOffset>("UpdatedAt").HasColumnType("datetimeoffset").HasColumnName("updated_at");
            b.HasKey("Id").HasName("pk_events");
            b.HasIndex("Slug").IsUnique().HasDatabaseName("ux_events_slug");
            b.ToTable("events");
        });

        modelBuilder.Entity("RevelMovies.Domain.Pairing.PairingSession", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedNever().HasColumnType("uniqueidentifier").HasColumnName("id");
            b.Property<string>("Code").IsRequired().HasMaxLength(6).HasColumnType("nvarchar(6)").HasColumnName("code");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnType("datetimeoffset").HasColumnName("created_at");
            b.Property<string>("DeviceToken").HasMaxLength(128).HasColumnType("nvarchar(128)").HasColumnName("device_token");
            b.Property<Guid?>("DisplayId").HasColumnType("uniqueidentifier").HasColumnName("display_id");
            b.Property<DateTimeOffset>("ExpiresAt").HasColumnType("datetimeoffset").HasColumnName("expires_at");
            b.Property<DateTimeOffset?>("PairedAt").HasColumnType("datetimeoffset").HasColumnName("paired_at");
            b.Property<string>("SessionToken").IsRequired().HasMaxLength(64).HasColumnType("nvarchar(64)").HasColumnName("session_token");
            b.HasKey("Id").HasName("pk_pairing_sessions");
            b.HasIndex("Code").HasDatabaseName("ix_pairing_sessions_code");
            b.HasIndex("SessionToken").IsUnique().HasDatabaseName("ux_pairing_sessions_session_token");
            b.ToTable("pairing_sessions");
        });

        modelBuilder.Entity("RevelMovies.Domain.Displays.Display", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedNever().HasColumnType("uniqueidentifier").HasColumnName("id");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnType("datetimeoffset").HasColumnName("created_at");
            b.Property<string>("DeviceTokenHash").IsRequired().HasMaxLength(64).HasColumnType("nvarchar(64)").HasColumnName("device_token_hash");
            b.Property<Guid>("EventId").HasColumnType("uniqueidentifier").HasColumnName("event_id");
            b.Property<DateTimeOffset?>("LastSeenAt").HasColumnType("datetimeoffset").HasColumnName("last_seen_at");
            b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)").HasColumnName("name");
            b.Property<int>("Status").HasColumnType("int").HasColumnName("status");
            b.Property<DateTimeOffset>("UpdatedAt").HasColumnType("datetimeoffset").HasColumnName("updated_at");
            b.HasKey("Id").HasName("pk_displays");
            b.HasIndex("DeviceTokenHash").IsUnique().HasDatabaseName("ux_displays_device_token_hash");
            b.HasIndex("EventId").HasDatabaseName("ix_displays_event_id");
            b.ToTable("displays");
        });

        modelBuilder.Entity("RevelMovies.Domain.Displays.Display", b =>
        {
            b.HasOne("RevelMovies.Domain.Events.Event", null)
                .WithMany()
                .HasForeignKey("EventId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired()
                .HasConstraintName("fk_displays_events_event_id");
        });
#pragma warning restore 612, 618
    }
}
