// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using RevelMovies.Infrastructure.Persistence;

#nullable disable

namespace RevelMovies.Infrastructure.Persistence.Migrations;

[DbContext(typeof(RevelMoviesDbContext))]
partial class RevelMoviesDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        modelBuilder.Entity("RevelMovies.Domain.Events.Event", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedNever().HasColumnType("uniqueidentifier").HasColumnName("id");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnType("datetimeoffset").HasColumnName("created_at");
            b.Property<DateTimeOffset?>("EndsAt").HasColumnType("datetimeoffset").HasColumnName("ends_at");
            b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)").HasColumnName("name");
            b.Property<string>("Slug").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)").HasColumnName("slug");
            b.Property<DateTimeOffset?>("StartsAt").HasColumnType("datetimeoffset").HasColumnName("starts_at");
            b.Property<int>("Status").HasColumnType("int").HasColumnName("status");
            b.Property<string>("TimeZone").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)").HasColumnName("time_zone");
            b.Property<DateTimeOffset>("UpdatedAt").HasColumnType("datetimeoffset").HasColumnName("updated_at");
            b.HasKey("Id").HasName("pk_events");
            b.HasIndex("Slug").IsUnique().HasDatabaseName("ux_events_slug");
            b.ToTable("events");
        });

        modelBuilder.Entity("RevelMovies.Domain.Pairing.PairingSession", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedNever().HasColumnType("uniqueidentifier").HasColumnName("id");
            b.Property<string>("Code").IsRequired().HasMaxLength(6).HasColumnType("nvarchar(6)").HasColumnName("code");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnType("datetimeoffset").HasColumnName("created_at");
            b.Property<string>("DeviceToken").HasMaxLength(128).HasColumnType("nvarchar(128)").HasColumnName("device_token");
            b.Property<Guid?>("DisplayId").HasColumnType("uniqueidentifier").HasColumnName("display_id");
            b.Property<DateTimeOffset>("ExpiresAt").HasColumnType("datetimeoffset").HasColumnName("expires_at");
            b.Property<DateTimeOffset?>("PairedAt").HasColumnType("datetimeoffset").HasColumnName("paired_at");
            b.Property<string>("SessionToken").IsRequired().HasMaxLength(64).HasColumnType("nvarchar(64)").HasColumnName("session_token");
            b.HasKey("Id").HasName("pk_pairing_sessions");
            b.HasIndex("Code").HasDatabaseName("ix_pairing_sessions_code");
            b.HasIndex("SessionToken").IsUnique().HasDatabaseName("ux_pairing_sessions_session_token");
            b.ToTable("pairing_sessions");
        });

        modelBuilder.Entity("RevelMovies.Domain.Displays.Display", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedNever().HasColumnType("uniqueidentifier").HasColumnName("id");
            b.Property<double?>("ClockOffsetMs").HasColumnType("float").HasColumnName("clock_offset_ms");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnType("datetimeoffset").HasColumnName("created_at");
            b.Property<string>("DeviceTokenHash").IsRequired().HasMaxLength(64).HasColumnType("nvarchar(64)").HasColumnName("device_token_hash");
            b.Property<Guid>("EventId").HasColumnType("uniqueidentifier").HasColumnName("event_id");
            b.Property<DateTimeOffset?>("LastClockSyncAt").HasColumnType("datetimeoffset").HasColumnName("last_clock_sync_at");
            b.Property<DateTimeOffset?>("LastSeenAt").HasColumnType("datetimeoffset").HasColumnName("last_seen_at");
            b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)").HasColumnName("name");
            b.Property<double?>("RoundTripMs").HasColumnType("float").HasColumnName("round_trip_ms");
            b.Property<int>("Status").HasColumnType("int").HasColumnName("status");
            b.Property<DateTimeOffset>("UpdatedAt").HasColumnType("datetimeoffset").HasColumnName("updated_at");
            b.HasKey("Id").HasName("pk_displays");
            b.HasIndex("DeviceTokenHash").IsUnique().HasDatabaseName("ux_displays_device_token_hash");
            b.HasIndex("EventId").HasDatabaseName("ix_displays_event_id");
            b.ToTable("displays");
        });

        modelBuilder.Entity("RevelMovies.Domain.Media.MediaAsset", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedNever().HasColumnType("uniqueidentifier").HasColumnName("id");
            b.Property<string>("Checksum").IsRequired().HasMaxLength(64).HasColumnType("nvarchar(64)").HasColumnName("checksum");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnType("datetimeoffset").HasColumnName("created_at");
            b.Property<double?>("DurationSeconds").HasColumnType("float").HasColumnName("duration_seconds");
            b.Property<Guid>("EventId").HasColumnType("uniqueidentifier").HasColumnName("event_id");
            b.Property<string>("FileName").IsRequired().HasMaxLength(260).HasColumnType("nvarchar(260)").HasColumnName("file_name");
            b.Property<long>("FileSize").HasColumnType("bigint").HasColumnName("file_size");
            b.Property<int?>("Height").HasColumnType("int").HasColumnName("height");
            b.Property<string>("MimeType").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)").HasColumnName("mime_type");
            b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)").HasColumnName("name");
            b.Property<string>("StorageKey").IsRequired().HasMaxLength(450).HasColumnType("nvarchar(450)").HasColumnName("storage_key");
            b.Property<int>("Type").HasColumnType("int").HasColumnName("type");
            b.Property<int?>("Width").HasColumnType("int").HasColumnName("width");
            b.HasKey("Id").HasName("pk_media_assets");
            b.HasIndex("Checksum").HasDatabaseName("ix_media_assets_checksum");
            b.HasIndex("EventId").HasDatabaseName("ix_media_assets_event_id");
            b.HasIndex("StorageKey").IsUnique().HasDatabaseName("ux_media_assets_storage_key");
            b.ToTable("media_assets");
        });

        modelBuilder.Entity("RevelMovies.Domain.DisplayGroups.DisplayGroup", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedNever().HasColumnType("uniqueidentifier").HasColumnName("id");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnType("datetimeoffset").HasColumnName("created_at");
            b.Property<Guid>("EventId").HasColumnType("uniqueidentifier").HasColumnName("event_id");
            b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)").HasColumnName("name");
            b.Property<DateTimeOffset>("UpdatedAt").HasColumnType("datetimeoffset").HasColumnName("updated_at");
            b.HasKey("Id").HasName("pk_display_groups");
            b.HasIndex("EventId").HasDatabaseName("ix_display_groups_event_id");
            b.ToTable("display_groups");
        });

        modelBuilder.Entity("RevelMovies.Domain.DisplayGroups.DisplayGroupMember", b =>
        {
            b.Property<Guid>("DisplayGroupId").HasColumnType("uniqueidentifier").HasColumnName("display_group_id");
            b.Property<Guid>("DisplayId").HasColumnType("uniqueidentifier").HasColumnName("display_id");
            b.HasKey("DisplayGroupId", "DisplayId").HasName("pk_display_group_members");
            b.HasIndex("DisplayId").HasDatabaseName("ix_display_group_members_display_id");
            b.ToTable("display_group_members");
        });

        modelBuilder.Entity("RevelMovies.Domain.Playlists.Playlist", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedNever().HasColumnType("uniqueidentifier").HasColumnName("id");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnType("datetimeoffset").HasColumnName("created_at");
            b.Property<Guid>("EventId").HasColumnType("uniqueidentifier").HasColumnName("event_id");
            b.Property<bool>("IsLoop").HasColumnType("bit").HasColumnName("is_loop");
            b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)").HasColumnName("name");
            b.Property<DateTimeOffset>("UpdatedAt").HasColumnType("datetimeoffset").HasColumnName("updated_at");
            b.HasKey("Id").HasName("pk_playlists");
            b.HasIndex("EventId").HasDatabaseName("ix_playlists_event_id");
            b.ToTable("playlists");
        });

        modelBuilder.Entity("RevelMovies.Domain.Playlists.PlaylistItem", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedNever().HasColumnType("uniqueidentifier").HasColumnName("id");
            b.Property<double?>("DurationSeconds").HasColumnType("float").HasColumnName("duration_seconds");
            b.Property<Guid>("MediaAssetId").HasColumnType("uniqueidentifier").HasColumnName("media_asset_id");
            b.Property<Guid>("PlaylistId").HasColumnType("uniqueidentifier").HasColumnName("playlist_id");
            b.Property<int>("Position").HasColumnType("int").HasColumnName("position");
            b.HasKey("Id").HasName("pk_playlist_items");
            b.HasIndex("MediaAssetId").HasDatabaseName("ix_playlist_items_media_asset_id");
            b.HasIndex("PlaylistId", "Position").IsUnique().HasDatabaseName("ux_playlist_items_playlist_position");
            b.ToTable("playlist_items");
        });

        modelBuilder.Entity("RevelMovies.Domain.Commands.CommandAcknowledgement", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedNever().HasColumnType("uniqueidentifier").HasColumnName("id");
            b.Property<DateTimeOffset?>("ClientTimestamp").HasColumnType("datetimeoffset").HasColumnName("client_timestamp");
            b.Property<Guid>("CommandId").HasColumnType("uniqueidentifier").HasColumnName("command_id");
            b.Property<string>("CommandType").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)").HasColumnName("command_type");
            b.Property<string>("Detail").HasMaxLength(500).HasColumnType("nvarchar(500)").HasColumnName("detail");
            b.Property<Guid>("DisplayId").HasColumnType("uniqueidentifier").HasColumnName("display_id");
            b.Property<DateTimeOffset>("ServerReceivedAt").HasColumnType("datetimeoffset").HasColumnName("server_received_at");
            b.Property<string>("Status").IsRequired().HasMaxLength(40).HasColumnType("nvarchar(40)").HasColumnName("status");
            b.HasKey("Id").HasName("pk_command_acknowledgements");
            b.HasIndex("DisplayId", "ServerReceivedAt").HasDatabaseName("ix_command_ack_display_received");
            b.HasIndex("DisplayId", "CommandId", "Status").IsUnique().HasDatabaseName("ux_command_ack_display_command_status");
            b.ToTable("command_acknowledgements");
        });

        modelBuilder.Entity("RevelMovies.Domain.Playback.DisplayPlaybackState", b =>
        {
            b.Property<Guid>("DisplayId").ValueGeneratedNever().HasColumnType("uniqueidentifier").HasColumnName("display_id");
            b.Property<double?>("ActualDurationSeconds").HasColumnType("float").HasColumnName("actual_duration_seconds");
            b.Property<Guid?>("ActualMediaAssetId").HasColumnType("uniqueidentifier").HasColumnName("actual_media_asset_id");
            b.Property<Guid?>("ActualPlaylistId").HasColumnType("uniqueidentifier").HasColumnName("actual_playlist_id");
            b.Property<int?>("ActualPlaylistIndex").HasColumnType("int").HasColumnName("actual_playlist_index");
            b.Property<double?>("ActualPositionSeconds").HasColumnType("float").HasColumnName("actual_position_seconds");
            b.Property<DateTimeOffset?>("ActualReportedAt").HasColumnType("datetimeoffset").HasColumnName("actual_reported_at");
            b.Property<string>("ActualState").IsRequired().HasMaxLength(40).HasColumnType("nvarchar(40)").HasColumnName("actual_state");
            b.Property<string>("ContentType").HasMaxLength(40).HasColumnType("nvarchar(40)").HasColumnName("content_type");
            b.Property<string>("DesiredState").IsRequired().HasMaxLength(40).HasColumnType("nvarchar(40)").HasColumnName("desired_state");
            b.Property<double?>("DriftMs").HasColumnType("float").HasColumnName("drift_ms");
            b.Property<string>("Health").IsRequired().HasMaxLength(40).HasColumnType("nvarchar(40)").HasColumnName("health");
            b.Property<Guid?>("LastCommandId").HasColumnType("uniqueidentifier").HasColumnName("last_command_id");
            b.Property<Guid?>("MediaAssetId").HasColumnType("uniqueidentifier").HasColumnName("media_asset_id");
            b.Property<double?>("PausedPositionSeconds").HasColumnType("float").HasColumnName("paused_position_seconds");
            b.Property<string>("PayloadJson").HasColumnType("nvarchar(max)").HasColumnName("payload_json");
            b.Property<Guid?>("PlaylistId").HasColumnType("uniqueidentifier").HasColumnName("playlist_id");
            b.Property<DateTimeOffset?>("StartedAt").HasColumnType("datetimeoffset").HasColumnName("started_at");
            b.Property<DateTimeOffset>("UpdatedAt").HasColumnType("datetimeoffset").HasColumnName("updated_at");
            b.HasKey("DisplayId").HasName("pk_display_playback_states");
            b.ToTable("display_playback_states");
        });

        modelBuilder.Entity("RevelMovies.Domain.Displays.Display", b =>
        {
            b.HasOne("RevelMovies.Domain.Events.Event", null)
                .WithMany()
                .HasForeignKey("EventId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired()
                .HasConstraintName("fk_displays_events_event_id");
        });

        modelBuilder.Entity("RevelMovies.Domain.Media.MediaAsset", b =>
        {
            b.HasOne("RevelMovies.Domain.Events.Event", null)
                .WithMany()
                .HasForeignKey("EventId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired()
                .HasConstraintName("fk_media_assets_events_event_id");
        });

        modelBuilder.Entity("RevelMovies.Domain.DisplayGroups.DisplayGroup", b =>
        {
            b.HasOne("RevelMovies.Domain.Events.Event", null)
                .WithMany()
                .HasForeignKey("EventId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired()
                .HasConstraintName("fk_display_groups_events_event_id");
        });

        modelBuilder.Entity("RevelMovies.Domain.DisplayGroups.DisplayGroupMember", b =>
        {
            b.HasOne("RevelMovies.Domain.Displays.Display", null)
                .WithMany()
                .HasForeignKey("DisplayId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired()
                .HasConstraintName("fk_display_group_members_displays_display_id");
            b.HasOne("RevelMovies.Domain.DisplayGroups.DisplayGroup", null)
                .WithMany()
                .HasForeignKey("DisplayGroupId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired()
                .HasConstraintName("fk_display_group_members_groups_group_id");
        });

        modelBuilder.Entity("RevelMovies.Domain.Playlists.Playlist", b =>
        {
            b.HasOne("RevelMovies.Domain.Events.Event", null)
                .WithMany()
                .HasForeignKey("EventId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired()
                .HasConstraintName("fk_playlists_events_event_id");
        });

        modelBuilder.Entity("RevelMovies.Domain.Playlists.PlaylistItem", b =>
        {
            b.HasOne("RevelMovies.Domain.Media.MediaAsset", null)
                .WithMany()
                .HasForeignKey("MediaAssetId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired()
                .HasConstraintName("fk_playlist_items_media_assets_media_asset_id");
            b.HasOne("RevelMovies.Domain.Playlists.Playlist", null)
                .WithMany()
                .HasForeignKey("PlaylistId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired()
                .HasConstraintName("fk_playlist_items_playlists_playlist_id");
        });

        modelBuilder.Entity("RevelMovies.Domain.Commands.CommandAcknowledgement", b =>
        {
            b.HasOne("RevelMovies.Domain.Displays.Display", null)
                .WithMany()
                .HasForeignKey("DisplayId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired()
                .HasConstraintName("fk_command_ack_displays_display_id");
        });

        modelBuilder.Entity("RevelMovies.Domain.Playback.DisplayPlaybackState", b =>
        {
            b.HasOne("RevelMovies.Domain.Displays.Display", null)
                .WithOne()
                .HasForeignKey("RevelMovies.Domain.Playback.DisplayPlaybackState", "DisplayId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired()
                .HasConstraintName("fk_display_playback_states_displays_display_id");
        });
#pragma warning restore 612, 618
    }
}
